### ISSUE TITLE
Kontaktinformasjon-felt er låst etter import sjølv om ingen slik informasjon fins i swagger-fil

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dataservice-catalog-gui#121]
Fra bruker:
> Nå har vi fått inn denne spesifikasjonen. Men det er en ting: Vi hadde ikke fylt ut contact informasjon i swagger. Likevel blir Kontaktinfomrasjonsfeltet i registreringsløsningen låst! Skal det være slik?

Gjelder følgande spesifikasjon:
https://api.app.mattilsynet.no/v1/kjoettkontrollhistorikk/v2/api-docs?group=ekstern

Eg har gjenskapt feilen ved import til demo-miljø. De aktuelle felta ser slik ut etter import:
![image](https://user-images.githubusercontent.com/1702357/169281781-ed91c3cb-dcea-4589-8e48-d1aaec50ded4.png)

**Comment by shenluna** [comment]
Testet ok
