### ISSUE TITLE
Importer spesifikasjon: Hjelpetekst ute av synk med supportert funksonalitet

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dataservice-catalog-gui#125]
Det står i teksten at brukar kan importere fil. Den knappen er ikkje tilgjengeleg. Vi må enten
1. lage funksjon for å importere fil, 
2. eller endre teksten.

Stemmer på (2), sidan vi ikkje har nokon stad å lagre fila.

Ref 
![image](https://user-images.githubusercontent.com/1702357/170945136-a216e26b-b382-4fb7-aece-3b65a39a4192.png)

**Comment by joebrreg** [comment]
Enig, vi endrer teksten til: "Du kan importere en eksisterende spesifikasjon via lenke. Felles datakatalog støtter ....".
@NilsOveTen Er det noen endring i versjoner av specs vi støtter? Og er dette en grei oppgave for å få Terje i gang?
