### ISSUE TITLE
Validering på endepunktsURL

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataservice-catalog-gui#21]
Mangler validering på gyldig URL her:
![image](https://user-images.githubusercontent.com/39513382/80211649-5cb5dd80-8636-11ea-9947-1ec1f09ddc92.png)

**Comment by lillelars** [comment]
@Chlenix 
Validering skal ikke slå inn dersom jeg har opprettet ETT endepunkt. Selv om bruker trykker på "Ny endepunktsbeskrivelse" og velger å ikke skrive inn noe her så bør ikke det kunne stoppe publisering.
![image](https://user-images.githubusercontent.com/39513382/81040557-e9b92c00-8eab-11ea-9e54-efd78dbaec85.png)

**Comment by lillelars** [comment]
@eggedosis Gidder du se på kommentaren min over... Dette er mulig UX ting.. Er det jeg sier riktig her eller skal bør valideringen slå inn med et tomt felt?

**Comment by eggedosis** [comment]
@lillelars Ja, det gir mening det du skriver. Jeg synes det er litt i overkant strengt å slå ned på et tomt felt som ikke er obligatorisk (kun én endepunktsURL er påkrevd).

**Comment by lillelars** [comment]
@Chlenix Ønsker en frontendvalidering på disse feltene at det er gyldig URL, for å hjelpe brukeren litt så han ikke bare fyller inn en string her.

**Comment by lillelars** [comment]
Denne fungerer som den skal nå. Lukker saken
