### ISSUE TITLE
Datatjenesteregistrering: Mediatypes: Søk i referencedata etter medietyper

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataservice-catalog-gui#22]
Forventer å kunne søke etter Mediatypes i referencedata... per nå fungerer ikke dette..

![image](https://user-images.githubusercontent.com/39513382/80211715-7a834280-8636-11ea-9c85-46bb33281556.png)

**Comment by azaxarov** [comment]
@valosnah  vi mangler SEARCH_API miljøvariabel i applikasjonen

**Comment by lillelars** [comment]
Dette fungerer nå som forventet.
Lukker denne.
