### ISSUE TITLE
Datatjenesteregistrering: Oppgi annen Mediatype kræsjer hele datatjenesteapplikasjonen

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataservice-catalog-gui#23]
@azaxarov  NB! Mulig det var dette feltet som gjorde at hele datatjenesteregistrering knakk... Når jeg forsøker å fylle inn i dette feltet kræsjer hele applikasjonen.

![image](https://user-images.githubusercontent.com/39513382/80211810-a8688700-8636-11ea-86c1-933fb6e2465e.png)

**Comment by azaxarov** [comment]
@valosnah vi mangler SEARCH_API miljøvariabel i applikasjonen

**Comment by lillelars** [comment]
Denne fungerer nå som forventet.
