### ISSUE TITLE
Legg til støtte for formater, fra kodelisten /eu/file-types

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/dataservice-catalog-gui#231]
Per nå støttes bare media types fra IANA, som er valgfri i dcat-ap-no

fra reference-data kan kodelisten som skal brukes hentes fra `/eu/file-types`

Blokkert av https://github.com/Informasjonsforvaltning/dataservice-catalog/issues/193

**Comment by NilsOveTen** [comment]
Før dette kan startes på trenger vi forslag til nye versjoner av div tekster, ref "Format" i registrering:

![Screenshot from 2023-03-10 14-42-19](https://user-images.githubusercontent.com/50194012/224331456-5d7aadcb-56d6-48cd-a330-b618ec5a8936.png)

**Comment by KurtStian** [comment]
Format

Velg format(er) for API’et.

Færre anbefalinger
Listen kommer fra EU publication office sin liste over offisielle filtyper: [File type](http://publications.europa.eu/resource/authority/file-type) ) Se spesifikasjonen [Datatjeneste: format](https://data.norge.no/specification/dcat-ap-no#Datatjeneste-format)

Tekst søkfelt: «Søk på og velg blant registrerte filtyper»
