### ISSUE TITLE
Koble ny datatjenestergistrering til inngang for datatjeneste/API-katalog

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataservice-catalog-gui#27]
Denne må gå til registreringen German har laget. Altså:
https://dataservice-catalog.staging.fellesdatakatalog.digdir.no/910244132

![image](https://user-images.githubusercontent.com/39513382/80454301-1f996600-892a-11ea-8c6e-ec0b61f55d2f.png)

**Comment by valosnah** [comment]
Trenger endringer i dataset-catalogue-gui i tillegg

**Comment by lillelars** [comment]
Denne er gjort, men reversert inntil vi får på plass høster og mapper ut mot portal.

**Comment by lillelars** [comment]
Funker nå som forventet. Lukker denne
