### ISSUE TITLE
Datatjenesteregistrering: skal være gyldig lenke

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataservice-catalog-gui#36]
Bør ha validering at dette er en gyldig lenke:

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/32b5056c-7962-4ea2-9e61-16da4b1d7281)

**Comment by shenluna** [comment]
Valideringen vises nå med en rød kant hvis tekstboksen ikke får riktig input
![image](https://user-images.githubusercontent.com/73637969/124240370-fa4e4c00-db1a-11eb-892d-5de7a20e1654.png)

Denne bør endres til en setning slik at brukeren forstår hva som er galt, eksempel fra datasett registrering
![image](https://user-images.githubusercontent.com/73637969/124240574-2669cd00-db1b-11eb-9f7d-432472c490f4.png)

**Comment by jeffreiffers** [comment]
Kan hende du må gjøre en hard refresh (CTRL + F5).

![image](https://user-images.githubusercontent.com/430997/127981716-28a4ad1e-127b-4f04-b674-626a35d278d8.png)

**Comment by shenluna** [comment]
Testet OK, nå vises feilmeldingene som tekst.
