### ISSUE TITLE
Opprette høsteendepunkt for FDK

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataservice-catalog-gui#40]
Europeisk dataportal må kunne høste oss.

https://www.europeandataportal.eu/data/datasets?locale=en&country=no&page=1

data.norge.no har kanskje noe vi kunne sett på?

**Comment by stigbd** [comment]
Dette er på plass her:
https://dataservice-catalog.fellesdatakatalog.digdir.no/catalogs
