### ISSUE TITLE
Oppdatere dataservice-gui med ny footer (og header)

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dataservice-catalog-gui#43]
- [x] Footerkomponenten fra fdk-kit skal inn i dataservice-gui

- [x] headerkomponent  inn i dataservice-gui

**Comment by shenluna** [comment]
Logoen må endres til ny logo. Se skissene her [https://www.figma.com/proto/SaWWNpmrAcWBEUht016ov6/API?node-id=1%3A3&viewport=249%2C-1658%2C0.36657339334487915&scaling=min-zoom](url)

**Comment by shenluna** [comment]
Testet i staging og verifisert i demo.
