### ISSUE TITLE
Feil i tekst i datatjenesteregistrering

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/dataservice-catalog-gui#45]
- [x] feil tekst ved sletting av datatjeneste (Er du sikker du vil slette denne behandlingsaktiviteten?) 
- [x] oppretter ny datatjeneste --> default tittel er "Åpne Data fra Enhetsregisteret - API Dokumentasjon"

**Comment by lillelars** [comment]
Dette er nå korrekt. Lukker saken.
