### ISSUE TITLE
Registreringsløsning API: Legge til eier ved søk 

### ISSUE THREAD

**Issue by sindresandvik2** [Informasjonsforvaltning/dataservice-catalog-gui#54]
Registrere API: Legge til ekstra kolonne ("Eier" /Publisher) i søkedropdown der bruker skal legge til tilknyttet datasettbeskrivelse

Se design her:
https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/343911175

**Comment by shenluna** [comment]
Begrep finnes ikke lenger i API-registrering, lukker dermed saken.
