### ISSUE TITLE
Add functionality to import dataservice formats in dataservice-catalog-gui

### ISSUE THREAD

**Issue by azaxarov** [Informasjonsforvaltning/dataservice-catalog-gui#57]
Når bruker importerer en spesifikasjon blir ikke formatene tatt med.

https://github.com/informasjonsforvaltning/dataservice-catalog/issues/74 tar for seg backend av dette

**Comment by lillelars** [comment]
Testet in staging, chrome. Fungerer nå som forventet. Lukker saken.
