### ISSUE TITLE
Ta bort "Legg til nytt endepunkt"-funksjon

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/dataservice-catalog-gui#60]
En datatjeneste kan bare ha en EndpointURL, derfor skal denne muligheten fjernes:
![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/0cf563d4-a1b8-4e04-ac8f-9f10bff11e8f)

**Comment by shenluna** [comment]
Testet OK
